TASK: TrainingAoA

DATASET:

    FEATURE_DATASET:
        TYPE: ViTCFeatureDataset
        BATCH_SIZE: 16
        WORKERS: 0
        FEATURE_PATH:
            FEATURES: data\vinvl_vinvl
            SCENE_TEXT: data\swintextspotter
            FASTTEXT: data\fasttext
            IMAGE: null
        SCENE_TEXT_THRESHOLD: 0.0
        MAX_SCENE_TEXT: 100
        WORD_EMBEDDING: ViFastText
        WORD_EMBEDDING_CACHE: null
        TOKENIZER:
            PRETRAINED_NAME: vit5-base
            PADDING_INDEX: 0
    DICT_DATASET:
        TYPE: ViTCDictionaryDataset
        BATCH_SIZE: 16
        WORKERS: 0
        FEATURE_PATH:
            FEATURES: data\vinvl_vinvl
            SCENE_TEXT: data\swintextspotter
            FASTTEXT: data\fasttext
            IMAGE: null
        SCENE_TEXT_THRESHOLD: 0.0
        MAX_SCENE_TEXT: 100
        WORD_EMBEDDING: ViFastText
        WORD_EMBEDDING_CACHE: null
        TOKENIZER:
            PRETRAINED_NAME: vit5-base
            PADDING_INDEX: 0
    MIN_FREQ: 1
    VOCAB:
        TYPE: OcrVocab
        TOKENIZER: null
        WORD_EMBEDDING: null
        WORD_EMBEDDING_CACHE: null
        MIN_FREQ: 1
        BOS_TOKEN: <bos>
        EOS_TOKEN: <eos>
        PAD_TOKEN: <pad>
        UNK_TOKEN: <unk>
        IMG_TOKEN: <img>
        FEAT_TOKEN: <feat>
        BOX_TOKEN: <box>
        OCR_TOKEN: <ocr>
        OCR_DET_TOKEN: <ocr_det>
        OCR_REC_TOKEN: <ocr_rec>
        QUESTION_TOKEN: <question>
        ANSWER_TOKEN: <answer>
        JSON_PATH:
            TRAIN: data\vitextcaps_train.json
            DEV: data\vitextcaps_dev.json
            TEST: data\vitextcaps_test.json
    JSON_PATH:
        TRAIN: data\vitextcaps_train.json
        DEV: data\vitextcaps_dev.json
        TEST: data\vitextcaps_test.json
TRAINING:
    CHECKPOINT_PATH: saved_models
    LEARNING_RATE: 0.0001
    LR_UPDATE: 15
    GRAD_CLIP: 1.
    RL_LEARNING_RATE: 0.000005
    WARMUP: 10000
    SCORE: CIDEr
    TRAINING_BEAM_SIZE: 1
    EVALUATING_BEAM_SIZE: 1
    PATIENCE: 10

MODEL:
    ARCHITECTURE: AoA_Model
    NAME: aoa_vinvl_swintestspotter
    DEVICE: cuda
    D_MODEL: 2048

    REFINE_LAYER:
      NUM_HEADS: 1
      STACK_LAYERS: 3
      FEATURE_SIZE: 2048
    
    DECODER:
      EMBEDDING_LAYERS: 3
      NUM_HEADS: 1
      FEATURE_SIZE: 2048
      EMBEDDING_SIZE: 2048
      VOCAB_SIZE: 36096
REMOVE_UNK_IN_PRED: True